### ISSUE TITLE
FastEnum.IsDefined<>() no longer accepts a number

### ISSUE THREAD

**Issue by OmarAl-Khateeb** [xin9le/FastEnum#45]
As the title says it no longer accepts a numeric value, rather accepts an enum is this intentional?

**Comment by xin9le** [comment]
We have removed the API that accepts numerical values in v2.
- https://github.com/xin9le/FastEnum/releases/tag/v2.0.0-preview1

This change was implemented to align with the behavior of the .NET standard `Enum.IsDefined<T>()` method. To utilize this functionality, please cast the numerical value to the target enum type.

```cs
// before
var x = FastEnum.IsDefined<HttpStatusCode>(123);

// after
var x = FastEnum.IsDefined((HttpStatusCode)123);
```
