### ISSUE TITLE
値の重複のあるEnumでGetNameの結果がずれる

### ISSUE THREAD

**Issue by kanahii** [xin9le/FastEnum#54]
FastEnum v2.0.2で値の重複のあるEnum(System.Windows.Input.Key等)に対してGetNameすると重複した分だけ結果がずれます。
(v1.8.0では問題なし)

.NET 8.0
console app
```cs
using FastEnumUtility;

var four = E.Four;
Console.WriteLine(four.ToName());                        // Two
Console.WriteLine(FastEnum.ToString(four));              // Two
Console.WriteLine(FastEnum.ToString<E, EBooster>(four)); // Four

enum E {
    Zero = 0,
    One = 1,
    Foo = 1, // duplicated
    Bar = 1, // duplicated
    Two = 2,
    Three = 3,
    Four = 4,
}

[FastEnum<E>]
partial class EBooster { }
```

**Comment by xin9le** [comment]
@kanahii 
Thank you for your kindness feedback. We greatly appreciate your assistance in identifying an issue that was overlooked during our testing phase. We have now released version 2.0.3, which addresses the reported concern. We kindly invite you to utilize this updated version.
